spring:
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    hikari: # springboot 2.0 \u6574\u5408\u4E86hikari ,\u636E\u8BF4\u8FD9\u662F\u76EE\u524D\u6027\u80FD\u6700\u597D\u7684java\u6570\u636E\u5E93\u8FDE\u63A5\u6C60
      username: root
      password: root
  jpa:
    show-sql: true
  redis:
     database: 0
     host: 127.0.0.1
     password:
     port: 6379
     timeout: 30000
     jedis:
       pool:
         max-active: -1
         max-idle: 10
         max-wait: -1
         min-idle: 1000
server:
  port: 8097

